language: cpp
cache: ccache

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - cmake
            - ninja-build
            - ccache

matrix:
  include:
    - name: "LibreSprite Linux"
      os: linux
      compiler: gcc
      sudo: required
      addons:
        apt:
          packages:
            - libx11-dev
            - libxcursor-dev
    - name: "LibreSprite OSX"
      os: osx
      osx_image: xcode7.3
      compiler: clang

env:
  - SHARED=OFF

before_install:
  - if [ "$SHARED" == "ON" ]; then sudo apt-get install -y libcurl4-openssl-dev libgif-dev libfreetype6-dev libjpeg-dev libz-dev libpng-dev libtinyxml-dev libpixman-1-dev liballegro4.2-dev ; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

before_script:
  - mkdir build
  - cd build
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        mkdir deps;
        cd deps;
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git;
        git clone https://github.com/aseprite/skia.git;
        export PATH="${PWD}/depot_tools:${PATH}";
        cd skia;
        git checkout aseprite-m53;
        python bin/sync-and-gyp;
        ninja -C out/Release dm;
        cd ../../;
        cmake -G Ninja .. -DCMAKE_OSX_ARCHITECTURES=x86_64 \
              -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7 \
              -DSKIA_DIR=/deps/skia \
              -DWITH_HarfBuzz=OFF'
  - if [ "$TRAVIS_OS_NAME" = "linux" ] then cmake -G Ninja .. -DUSE_SHARED_CURL=$SHARED -DUSE_SHARED_GIFLIB=$SHARED -DUSE_SHARED_FREETYPE=$SHARED -DUSE_SHARED_JPEGLIB=$SHARED -DUSE_SHARED_ZLIB=$SHARED -DUSE_SHARED_LIBPNG=$SHARED -DUSE_SHARED_TINYXML=$SHARED -DUSE_SHARED_PIXMAN=$SHARED -DUSE_SHARED_ALLEGRO4=$SHARED -DENABLE_TESTS=ON

script:
  - ninja libresprite
  - "ctest --output-on-failure"
  - cd "${TRAVIS_BUILD_DIR}"
  - ccache -s
